prius:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint_base_link_connection:
    type: effort_controllers/JointPositionController
    joint: base_link_connection
    pid: {p: 100.0, i: 0.01, d: 10.0}